<?php

namespace ModuleExample\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExampleEntitWithDateTimeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExampleEntitWithDateTimeyRepository extends EntityRepository
{
}
